### ISSUE TITLE
Pakol can still be found in arsenal

### ISSUE THREAD

**Issue by Tinter** [fparma/fp_uniforms#52]
Ye.

**Comment by Cuel** [comment]
Yeah mallow know this. It was also in the change log 

Dunno if I extract textures or just remove it

**Comment by Tinter** [comment]
CUP covers the pakol now so it should be removed.

**Comment by Cuel** [comment]
@Mallow234 config-hide it?

**Comment by Mallow234** [comment]
This is now removed.
